CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY NOT NULL,
    USERNAME TEXT NOT NULL,
    PWD TEXT NOT NULL,
    NICKNAME TEXT DEFAULT "" NOT NULL,
    GENDER TEXT DEFAULT "沃尔玛购物袋" NOT NULL,
    DESCRIPT TEXT DEFAULT "这人太懒了，备注都懒得写" NOT NULL,
    RANK INT DEFAULT 0 NOT NULL,
    BINDS TEXT DEFAULT "" NOT NULL,
    BYEAR INT DEFAULT 2024 NOT NULL,
    BMONTH INT DEFAULT 2 NOT NULL,
    BDAY INT DEFAULT 1 NOT NULL,
    TAGS TEXT DEFAULT "" NOT NULL
);
CREATE UNIQUE INDEX USERNAME_INDEX ON USERS (USERNAME);
CREATE INDEX BIRTHDAY_INDEX ON USERS (BYEAR,BMONTH,BDAY);
